name: reproduce-1600

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm install
         
