name: testing mise

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create mise.toml
        shell: bash
        run: |
          cat > mise.toml <<'EOF'
          [tools]
          node = "26"
          EOF
      - uses: actions/checkout@v6
      
      - uses: gowridurgad/setup-node@mise-testing
        with:
          node-version-file: 'mise.toml'
      - name: Verify
        shell: bash
        run: |
          node --version
          
      - run: npm install
