name: testing mise

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gowridurgad/setup-node@mise-teating
        with:
          node-version-file: mise.toml
      - run: npm install
