name: Testing1190

on:
  workflow_dispatch:

jobs:
  test-cache-key:
    runs-on: self-hosted
       
        
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v6



      - name: Setup Node
        id: setup
        # uses: actions/setup-node@v6
        # uses: alexdunae/setup-node@main
        uses: gowridurgad/setup-node@testing-1009
        with:
          node-version: '24'
          cache: yarn
  
      - name: Install deps
        run: yarn install
      
      - name: Show cache-key vs cache-matched-key   
        shell: bash
        run: |
          echo "cache-key         : ${{ steps.setup.outputs.cache-key }}"
          echo "cache-matched-key : ${{ steps.setup.outputs.cache-matched-key }}"
          echo "cache-hit         : ${{ steps.setup.outputs.cache-hit }}"
     
